### PR TITLE
Allow datastore clusters to be nested in folders

### PR DESCRIPTION
**Pull request by jpalermo**
Currently datastore clusters must be top level for the cpi to find them, this change will add functionality to search for them within storage folders in vcenter.

Slashes are not valid in folder or datastore cluster names, they must be escaped in vCenter, so we use slash as our expected folder delimiter.

For the "pattern" matching case, after splitting on slashes, we have to convert each segment into a regular expression in case the user is relying on that for wildcard matching. As regexes don't use forward slashes, and the entity names they are searching for also can't have slashes, this should be safe.

The unused StoragePod.find method was also removed

### CODE REVIEW

**Review by lnguyen — APPROVED** [review]
LGTM

**Comment by jpalermo** [comment]
We realized that this behavior will not work if you specify a datastore pattern that has multiple regex options already. i.e. `/folder1/datastore1|/folder2/datastore2|datastore3`

**Comment by jpalermo** [comment]
We've updated `search_in_subfolders` to now build a full index of datastore clusters (StoragePods) and the folders they are in, then use the provided pattern to match the appropriate ones.

**Review by cunnie — APPROVED** [review]
LGTM

**Comment by rkoster** [comment]
@lnguyen could you take an other look at the changes?

**Review by lnguyen — APPROVED** [review]
LGTM

**Pull request merged**
