### PR TITLE
Manual url-encode for the square brackets in URL path

### LINKED ISSUE #288: CPI fails to delete VM with use_policy_api
**Describe the bug**
When use_policy_api is turned on and VM is going to be removed there is a problem with removal from all NSGroups. Below error is returned from NSX-T Policy API: `The URI is invalid`. Issue happen when there are some NSGroups with `[` or `]` in the name/path.

**To Reproduce**
1. Create LB service and some virtual server in NSX-T using Polic API. NSX-T should create some Groups in the Inventory associated with that LB.
2. Create an instance and try to update/remove.
3. There is an error when VM is going to be removed from Groups.

**CPI Error Log**
```
I, [2021-03-08T14:18:08.164605 #1080920]  INFO -- : Removing vm: vm-b0a1f80e-a709-4c24-bc0c-e90c3762725b from all Policy Groups it is part of
I, [2021-03-08T14:18:08.164637 #1080920]  INFO -- : Gathering all Policy Groups
I, [2021-03-08T14:18:08.500597 #1080920]  INFO -- : Found 27 Policy Groups
I, [2021-03-08T14:18:08.500670 #1080920]  INFO -- : Searching for Policy Group with group id: NLB.PoolLB.[fb1b4b2f-16e0-4879-86d2-8dbdcf97d3ce][0b61d177-c090-4f13-8271-8c3a8e42fd83]
I, [2021-03-08T14:18:08.508686 #1080920]  INFO -- : Failed to find Policy Group: NLB.PoolLB.[fb1b4b2f-16e0-4879-86d2-8dbdcf97d3ce][0b61d177-c090-4f13-8271-8c3a8e42fd83] with error #<JSON::ParserError: 783: unexpected token at '{
  "module_name": "common-services"
  "error_message": "The URI is invalid"
  "error_code": 60211
  "details": ""
}'>
I, [2021-03-08T14:18:08.508844 #1080920]  INFO -- : Failed to remove VM from Groups with message 783: unexpected token at '{
  "module_name": "common-services"
  "error_message": "The URI is invalid"
  "error_code": 60211
  "details": ""
}'
I, [2021-03-08T14:18:08.509277 #1080920]  INFO -- [req_id ]: Finished delete_vm in 80.78 seconds
D, [2021-03-08T14:18:08.509500 #1080920] DEBUG -- : Running method 'Logout'...
'
[cpiCmdRunner] 2021/03/08 14:18:08 DEBUG - Rescued Unknown: 783: unexpected token at '{
  "module_name": "common-services"
  "error_message": "The URI is invalid"
  "error_code": 60211
  "details": ""
}'. backtrace: /home/ubuntu/.bosh/installations/0c078174-c765-43f9-557d-88e5f01a3b84/packages/vsphere_cpi/vendor/bundle/ruby/2.6.0/gems/json-2.3.0/lib/json/common.rb:156:in `parse'
/home/ubuntu/.bosh/installations/0c078174-c765-43f9-557d-88e5f01a3b84/packages/vsphere_cpi/vendor/bundle/ruby/2.6.0/gems/json-2.3.0/lib/json/common.rb:156:in `parse'
/home/ubuntu/.bosh/installations/0c078174-c765-43f9-557d-88e5f01a3b84/packages/vsphere_cpi/lib/nsxt_policy_client/nsxt_policy_client/api_client.rb:66:in `call_api'
/home/ubuntu/.bosh/installations/0c078174-c765-43f9-557d-88e5f01a3b84/packages/vsphere_cpi/lib/nsxt_policy_client/nsxt_policy_client/api/policy_inventory_groups_groups_api.rb:2240:in `read_group_for_domain_with_http_info'
/home/ubuntu/.bosh/installations/0c078174-c765-43f9-557d-88e5f01a3b84/packages/vsphere_cpi/lib/nsxt_policy_client/nsxt_policy_client/api/policy_inventory_groups_groups_api.rb:2199:in `read_group_for_domain'
/home/ubuntu/.bosh/installations/0c078174-c765-43f9-557d-88e5f01a3b84/packages/vsphere_cpi/lib/cloud/vsphere/nsxt_policy_provider.rb:76:in `retrieve_group'
/home/ubuntu/.bosh/installations/0c078174-c765-43f9-557d-88e5f01a3b84/packages/vsphere_cpi/lib/cloud/vsphere/nsxt_policy_provider.rb:47:in `block (2 levels) in remove_vm_from_groups'
/home/ubuntu/.bosh/installations/0c078174-c765-43f9-557d-88e5f01a3b84/packages/vsphere_cpi/lib/cloud/vsphere/nsxt_policy_provider.rb:61:in `retry_on_conflict'
/home/ubuntu/.bosh/installations/0c078174-c765-43f9-557d-88e5f01a3b84/packages/vsphere_cpi/lib/cloud/vsphere/nsxt_policy_provider.rb:46:in `block in remove_vm_from_groups'
/home/ubuntu/.bosh/installations/0c078174-c765-43f9-557d-88e5f01a3b84/packages/vsphere_cpi/lib/cloud/vsphere/nsxt_policy_provider.rb:45:in `each'
/home/ubuntu/.bosh/installations/0c078174-c765-43f9-557d-88e5f01a3b84/packages/vsphere_cpi/lib/cloud/vsphere/nsxt_policy_provider.rb:45:in `remove_vm_from_groups'
/home/ubuntu/.bosh/installations/0c078174-c765-43f9-557d-88e5f01a3b84/packages/vsphere_cpi/lib/cloud/vsphere/cloud.rb:495:in `block in delete_vm'
/home/ubuntu/.bosh/installations/0c078174-c765-43f9-557d-88e5f01a3b84/packages/vsphere_cpi/vendor/bundle/ruby/2.6.0/gems/bosh_common-1.3262.24.0/lib/common/thread_formatter.rb:49:in `with_thread_name'
/home/ubuntu/.bosh/installations/0c078174-c765-43f9-557d-88e5f01a3b84/packages/vsphere_cpi/lib/cloud/vsphere/cloud.rb:462:in `delete_vm'
/home/ubuntu/.bosh/installations/0c078174-c765-43f9-557d-88e5f01a3b84/packages/ruby-2.6.5-r0.29.0/lib/ruby/2.6.0/forwardable.rb:230:in `delete_vm'
/home/ubuntu/.bosh/installations/0c078174-c765-43f9-557d-88e5f01a3b84/packages/vsphere_cpi/vendor/bundle/ruby/2.6.0/gems/bosh_cpi-2.5.0/lib/bosh/cpi/cli.rb:89:in `public_send'
/home/ubuntu/.bosh/installations/0c078174-c765-43f9-557d-88e5f01a3b84/packages/vsphere_cpi/vendor/bundle/ruby/2.6.0/gems/bosh_cpi-2.5.0/lib/bosh/cpi/cli.rb:89:in `run'
/home/ubuntu/.bosh/installations/0c078174-c765-43f9-557d-88e5f01a3b84/packages/vsphere_cpi/bin/vsphere_cpi:48:in `<top (required)>'
/home/ubuntu/.bosh/installations/0c078174-c765-43f9-557d-88e5f01a3b84/packages/ruby-2.6.5-r0.29.0/lib/ruby/site_ruby/2.6.0/bundler/cli/exec.rb:63:in `load'
/home/ubuntu/.bosh/installations/0c078174-c765-43f9-557d-88e5f01a3b84/packages/ruby-2.6.5-r0.29.0/lib/ruby/site_ruby/2.6.0/bundler/cli/exec.rb:63:in `kernel_load'
/home/ubuntu/.bosh/installations/0c078174-c765-43f9-557d-88e5f01a3b84/packages/ruby-2.6.5-r0.29.0/lib/ruby/site_ruby/2.6.0/bundler/cli/exec.rb:28:in `run'
/home/ubuntu/.bosh/installations/0c078174-c765-43f9-557d-88e5f01a3b84/packages/ruby-2.6.5-r0.29.0/lib/ruby/site_ruby/2.6.0/bundler/cli.rb:476:in `exec'
/home/ubuntu/.bosh/installations/0c078174-c765-43f9-557d-88e5f01a3b84/packages/ruby-2.6.5-r0.29.0/lib/ruby/site_ruby/2.6.0/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/home/ubuntu/.bosh/installations/0c078174-c765-43f9-557d-88e5f01a3b84/packages/ruby-2.6.5-r0.29.0/lib/ruby/site_ruby/2.6.0/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
/home/ubuntu/.bosh/installations/0c078174-c765-43f9-557d-88e5f01a3b84/packages/ruby-2.6.5-r0.29.0/lib/ruby/site_ruby/2.6.0/bundler/vendor/thor/lib/thor.rb:399:in `dispatch'
/home/ubuntu/.bosh/installations/0c078174-c765-43f9-557d-88e5f01a3b84/packages/ruby-2.6.5-r0.29.0/lib/ruby/site_ruby/2.6.0/bundler/cli.rb:30:in `dispatch'
/home/ubuntu/.bosh/installations/0c078174-c765-43f9-557d-88e5f01a3b84/packages/ruby-2.6.5-r0.29.0/lib/ruby/site_ruby/2.6.0/bundler/vendor/thor/lib/thor/base.rb:476:in `start'
/home/ubuntu/.bosh/installations/0c078174-c765-43f9-557d-88e5f01a3b84/packages/ruby-2.6.5-r0.29.0/lib/ruby/site_ruby/2.6.0/bundler/cli.rb:24:in `start'
/home/ubuntu/.bosh/installations/0c078174-c765-43f9-557d-88e5f01a3b84/packages/ruby-2.6.5-r0.29.0/lib/ruby/gems/2.6.0/gems/bundler-2.1.2/exe/bundle:46:in `block in <top (required)>'
/home/ubuntu/.bosh/installations/0c078174-c765-43f9-557d-88e5f01a3b84/packages/ruby-2.6.5-r0.29.0/lib/ruby/site_ruby/2.6.0/bundler/friendly_errors.rb:123:in `with_friendly_errors'
/home/ubuntu/.bosh/installations/0c078174-c765-43f9-557d-88e5f01a3b84/packages/ruby-2.6.5-r0.29.0/lib/ruby/gems/2.6.0/gems/bundler-2.1.2/exe/bundle:34:in `<top (required)>'
/home/ubuntu/.bosh/installations/0c078174-c765-43f9-557d-88e5f01a3b84/packages/ruby-2.6.5-r0.29.0/bin/bundle:23:in `load'
/home/ubuntu/.bosh/installations/0c078174-c765-43f9-557d-88e5f01a3b84/packages/ruby-2.6.5-r0.29.0/bin/bundle:23:in `<main>'
Failed (00:01:31)
```

**Expected behavior**
VM is removed without any problems

**Release Version & Related Info (please complete the following information):**
 - CPI Version: 55
 - BOSH Director Version: 270.11.0
 - Stemcell Name & Version: bosh-stemcell-621.51-vsphere-esxi-ubuntu-xenial-go_agent
 - vCenter Version: 7.0.1
 - NSX-T Version: 3.0.2.0.0.16887200

**Additional context**
Problem seems to be caused by not escaped `[` or `]` from the name. It basically happen here: https://github.com/cloudfoundry/bosh-vsphere-cpi-release/blob/master/src/vsphere_cpi/lib/cloud/vsphere/nsxt_policy_provider.rb#L73
when CPI tries to request the NSX-T Policy API for Group details. During that process the URL with full path to the Group is created. Part of this URL is Group ID, which in most cases is just a UUID but sometimes it may be a bit more complicated (e.g. `NLB.PoolLB.[fb1b4b2f-16e0-4879-86d2-8dbdcf97d3ce][0b61d177-c090-4f13-8271-8c3a8e42fd83]`) and in that cases NSX-T Policy API returns an error because this URI.encode: https://github.com/cloudfoundry/bosh-vsphere-cpi-release/blob/7e48988237f84982f7f22e73aa5131c16c2990d6/src/vsphere_cpi/lib/nsxt_policy_client/nsxt_policy_client/api_client.rb#L270 does not escape `[` or `]`.
I have tried and confirmed that if you escape those characters then NSX-T API returns correct response.

### PR DESCRIPTION
**Pull request by miro-grapeup**
# Description

According to the submitted issue #288 there is an issue with NSX-T Policy API when URL path (eg. GroupID) contains the square brackets. In order to fix that problem we need to escape them.

## Related PR and Issues
Fixes #288 

## Impacted Areas in Application
- NSX-T PolicyAPI client

## Type of change
- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?
- Verified with existing environment:
    ```
    CPI Version: 55+dev.1
    BOSH Director Version: 270.11.0
    Stemcell Name & Version: bosh-stemcell-621.51-vsphere-esxi-ubuntu-xenial-go_agent
    vCenter Version: 7.0.1
    NSX-T Version: 3.0.2.0.0.16887200
    ```
- Run unit-tests:
    ```
    Finished in 5.82 seconds (files took 19.24 seconds to load)
    839 examples, 0 failures, 71 pending
    ```

# Checklist:

- [x] My code follows the standard ruby style guide
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by moleske** [comment]
Hi @miro-grapeup thank you for the PR.  The file you changed is actually generated by a rake task.  The file you need to update in addition is https://github.com/cloudfoundry/bosh-vsphere-cpi-release/blob/master/src/vsphere_cpi/data/swagger-nsxt-template/api_client.mustache#L267 .  After updating the mustache template, you will need to regenerate the swagger clients for manager and policy api.  The rakefile contains the two tasks, [manager](https://github.com/cloudfoundry/bosh-vsphere-cpi-release/blob/master/src/vsphere_cpi/data/swagger-nsxt-template/api_client.mustache#L267l) and [policy](https://github.com/cloudfoundry/bosh-vsphere-cpi-release/blob/master/src/vsphere_cpi/Rakefile#L88).  Running those tasks will update the file you initially changed, along with the manager api client.

Please also squash down to one commit when you make these changes.

If you have trouble doing this, let us know and we can go make these changes for you.

**Comment by syslxg** [comment]
Hi @miro-grapeup, we took your initial commit and made some changes. the new commit is https://github.com/cloudfoundry/bosh-vsphere-cpi-release/commit/5a7000c00f7da88224a73ba199fa5526dad64a97

We are going to close this PR. Please let us know if you see any issues.

**Comment by miro-grapeup** [comment]
Hi @syslxg and @moleske thanks a lot for your changes! By the way I would like to mention some possible issues with the current logic related to NSGroups.
1. It is based on NSXTPolicy::Condition - which is limited to 5 per each NSXT group. It means that only 5 VMs can be added to the single group.
2. The logic for removal VM from group can cause problems if user/bosh wants to remove the VM that was added first. In that case NSX-T will fail because there will be odd number of items in the expressions array. Eg. `VM1_condition <conjuction> VM2_condition <conjuction> VM3_condition` -> remove VM1 -> `<conjuction> VM2_condition <conjuction> VM3_condition`
3. The best approach will be usage of vm_fabric_svc and ExternalIdExpression, e.g for adding VM to the group:
```
virtual_machines = vm_fabric_svc.list_virtual_machines(display_name: vm.cid).results
logger.info("Virtual Machines fetched : #{virtual_machines.pretty_inspect}") if virtual_machines.length > 1
raise VirtualMachineNotFound.new(vm.cid) if virtual_machines.empty?
external_id = virtual_machines.first.external_id
(...)
# If there is no ExternalIDExpression expression in the group then create one
# else use the existing one or iterate over all expressions with type: ExternalIDExpression
# If externalExpression contains the external_id then return
# If there is no externalIdExpression which contains external_id then push external_id to the last (or with some concrete ID) externalIdExpression
(...)
external_ids << external_id
group_obj.expression << NSXTPolicy::ExternalIDExpression.new(resource_type: 'ExternalIDExpression',
                                                                    member_type: 'VirtualMachine',
                                                                    external_ids: external_ids)
```

What do you think? Do you want some another PR for that?

**Comment by moleske** [comment]
@miro-grapeup - We'd love a PR!  Thanks for pointing this out, this is really good to know.

**Pull request closed without merging**
